### PR TITLE
interpreted Aztec

### PR DESCRIPTION
**Pull request by edwardtay**

### CODE REVIEW

**Comment by BrennerSpear** [comment]
It should update this snapshot file: https://github.com/edwardtay/evm-translator/blob/main/src/__tests__/__snapshots__/Interpreter.test.js.snap

**Comment by BrennerSpear** [comment]
Is there only 1 function on that contract, or are there multiple? I would guess there's also at least a withdraw function also?

**Comment by edwardtay** [comment]
> Is there only 1 function on that contract, or are there multiple? I would guess there's also at least a withdraw function also?

I think only that 1 function is applicable here.

Aztec is a privacy zk rollup, so only deposits are publicly shown, withdrawals can only be called using [processRollup](https://bloxy.info/functions/06011a46) by privilege role

**Comment by BrennerSpear** [comment]
> It should update this snapshot file: https://github.com/edwardtay/evm-translator/blob/main/src/__tests__/__snapshots__/Interpreter.test.js.snap

Could you please update this first?

**Pull request closed without merging**
